commit_message: Breaking news! File %original_file_name% has new translations in %language%
append_commit_message: false
files:
  - source: /Temp.po
    translation: /Localization/%locale%/%locale_with_underscore%.po
